# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TapCounter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapCounter

  # Install RxSwift
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  # Install Swift Lint
  pod 'SwiftLint'
  target 'TapCounterTests' do
    inherit! :search_paths
    # Pods for testing

    # Install RxSwift for Test Target
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
  end

  target 'TapCounterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
